title: Air Gyaan
avatar: Avatar de {0}
lightMode: Modo claro
darkMode: Modo oscuro
home: Inicio
explore: Explorar
newPost: Nueva publicación
notifications: Notifs
me: Yo
ok: Aceptar
cancel: Cancelar

